
name: Backup Database



jobs:
  mongodb-backup:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository (if needed for further actions)
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Set up Node.js or other environment (if required)
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Step 3: Dump the MongoDB database
      - name: Backup MongoDB
        env:
          MONGO_URI: ${{ secrets.MONGO_URI }}
        run: |
          # Install MongoDB tools
          sudo apt-get update && sudo apt-get install -y mongodb-clients
          # Create a backup directory
          mkdir -p backup
          # Dump the database into a compressed file
          mongodump --uri="$MONGO_URI" --archive=./backup/mongodb_backup_$(date +'%Y-%m-%d').gz --gzip

      # Step 4: Optionally upload to the repository
      - name: Commit and Push Backup to Repository
        if: success()
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --local user.name "github-actions[bot]"
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git add backup/
          git commit -m "MongoDB Backup $(date +'%Y-%m-%d')"
          git push

      # Step 5: Optionally upload to AWS S3 (replace with your bucket and credentials)
      - name: Upload Backup to S3
        if: success()
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
        run: |
          # Install AWS CLI
          sudo apt-get update && sudo apt-get install -y awscli
          # Upload backup to S3 bucket
          aws s3 cp ./backup/mongodb_backup_$(date +'%Y-%m-%d').gz s3://your-s3-bucket-name/backups/
