name: Compile LaTeX Documents

on:
  push:
    paths:
      - "**.tex" # Trigger on any .tex file changes in any folder.
  pull_request:
    paths:
      - "**.tex" # Also trigger on .tex file changes in pull requests.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Find LaTeX files from git diff
        id: find_tex_files
        run: |
          tex_files=$(git diff --name-only HEAD^ HEAD | grep '.tex$' | tr '\n' ' ')
          echo "files=$tex_files" >> $GITHUB_OUTPUT

      - name: Run LaTeX Action
        uses: xu-cheng/latex-action@v3
        with:
          root_file: ${{ steps.find_tex_files.outputs.files }}
